### ISSUE TITLE
Neovide does not start with kwin 5.25 in wayland session (wayland-client error)

### ISSUE THREAD

**Issue by barklan** [neovide/neovide#1356]
**Describe the bug**
Since upgrade to [KDE Plasma 5.25](https://kde.org/announcements/plasma/5/5.25.0/) Neovide does not start. Release build produces no output. Debug build produces the following:

```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
```

**To Reproduce**
1. Use KDE Plasma (with kwin) 5.25 in Wayland session.
2. `neovide` does not start

**Expected behavior**
Neovide starting.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Arch Linux with KDE Plasma 5.25 in Wayland session.
 - Neovide 0.9.0 (latest master, rev [7a3bf52](https://github.com/neovide/neovide/commit/7a3bf522edcdf24b87b082d800177b8099a35846))
 -  Neovim 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

```
TRACE [neovide] Neovide version: 0.9.0
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
```

**Additional context**

Output of `WAYLAND_DEBUG=1 ./target/debug/neovide`:

<details>
  <summary>Click me</summary>

```
[1617421.741]  -> wl_display@1.get_registry(new id wl_registry@2)
[1617421.806]  -> wl_display@1.sync(new id wl_callback@3)
[1617425.226] wl_display@1.delete_id(3)
[1617425.246] wl_registry@2.global(1, "wl_compositor", 5)
[1617425.316]  -> wl_registry@2.bind(1, "wl_compositor", 5, new id [unknown]@4)
[1617425.345] wl_registry@2.global(2, "zwp_tablet_manager_v2", 1)
[1617425.359] wl_registry@2.global(3, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[1617425.372] wl_registry@2.global(5, "xdg_wm_base", 4)
[1617425.387] wl_registry@2.global(6, "zwlr_layer_shell_v1", 3)
[1617425.403] wl_registry@2.global(7, "zxdg_decoration_manager_v1", 1)
[1617425.418]  -> wl_registry@2.bind(7, "zxdg_decoration_manager_v1", 1, new id [unknown]@5)
[1617425.434] wl_registry@2.global(8, "wp_viewporter", 1)
[1617425.444] wl_registry@2.global(9, "wl_shm", 1)
[1617425.464]  -> wl_registry@2.bind(9, "wl_shm", 1, new id [unknown]@6)
[1617425.489] wl_registry@2.global(10, "wl_seat", 7)
[1617425.505]  -> wl_registry@2.bind(10, "wl_seat", 6, new id [unknown]@7)
[1617425.536] wl_registry@2.global(11, "zwp_pointer_gestures_v1", 3)
[1617425.547] wl_registry@2.global(12, "zwp_pointer_constraints_v1", 1)
[1617425.566]  -> wl_registry@2.bind(12, "zwp_pointer_constraints_v1", 1, new id [unknown]@8)
[1617425.591] wl_registry@2.global(13, "zwp_relative_pointer_manager_v1", 1)
[1617425.604]  -> wl_registry@2.bind(13, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@9)
[1617425.619] wl_registry@2.global(14, "wl_data_device_manager", 3)
[1617425.630] wl_registry@2.global(15, "zwlr_data_control_manager_v1", 2)
[1617425.642] wl_registry@2.global(16, "zwp_primary_selection_device_manager_v1", 1)
[1617425.653] wl_registry@2.global(17, "org_kde_kwin_idle", 1)
[1617425.662] wl_registry@2.global(18, "zwp_idle_inhibit_manager_v1", 1)
[1617425.675] wl_registry@2.global(19, "org_kde_plasma_shell", 7)
[1617425.686] wl_registry@2.global(20, "org_kde_kwin_appmenu_manager", 1)
[1617425.697] wl_registry@2.global(21, "org_kde_kwin_server_decoration_palette_manager", 1)
[1617425.708] wl_registry@2.global(23, "org_kde_plasma_virtual_desktop_management", 2)
[1617425.719] wl_registry@2.global(25, "org_kde_kwin_shadow_manager", 2)
[1617425.731] wl_registry@2.global(26, "org_kde_kwin_dpms_manager", 1)
[1617425.742] wl_registry@2.global(27, "org_kde_kwin_server_decoration_manager", 1)
[1617425.754] wl_registry@2.global(28, "kde_output_management_v2", 2)
[1617425.765] wl_registry@2.global(29, "kde_primary_output_v1", 2)
[1617425.777] wl_registry@2.global(30, "zxdg_output_manager_v1", 3)
[1617425.788] wl_registry@2.global(31, "wl_subcompositor", 1)
[1617425.802]  -> wl_registry@2.bind(31, "wl_subcompositor", 1, new id [unknown]@10)
[1617425.817] wl_registry@2.global(32, "zxdg_exporter_v2", 1)
[1617425.828] wl_registry@2.global(33, "zxdg_importer_v2", 1)
[1617425.838] wl_registry@2.global(35, "xdg_activation_v1", 1)
[1617425.852] wl_registry@2.global(36, "wp_drm_lease_device_v1", 1)
[1617425.862] wl_registry@2.global(39, "wl_drm", 2)
[1617425.874] wl_registry@2.global(40, "zwp_linux_dmabuf_v1", 4)
[1617425.883] wl_registry@2.global(41, "kde_output_device_v2", 2)
[1617425.894] wl_registry@2.global(42, "wl_output", 3)
[1617425.903]  -> wl_registry@2.bind(42, "wl_output", 3, new id [unknown]@11)
[1617425.934] wl_registry@2.global(44, "zwp_text_input_manager_v2", 1)
[1617425.946] wl_registry@2.global(45, "zwp_text_input_manager_v3", 1)
[1617425.959]  -> wl_registry@2.bind(45, "zwp_text_input_manager_v3", 1, new id [unknown]@12)
[1617425.978] wl_registry@2.global(46, "org_kde_kwin_contrast_manager", 2)
[1617425.988] wl_registry@2.global(47, "org_kde_kwin_blur_manager", 1)
[1617426.000] wl_registry@2.global(48, "org_kde_kwin_slide_manager", 1)
[1617426.015] wl_callback@3.done(25429)
[1617426.024]  -> wl_display@1.sync(new id wl_callback@3)
[1617426.112] wl_display@1.delete_id(3)
[1617426.117] wl_shm@6.format(0)
[1617426.135] wl_shm@6.format(1)
[1617426.139] wl_shm@6.format(808669761)
[1617426.142] wl_shm@6.format(808669784)
[1617426.146] wl_shm@6.format(808665665)
[1617426.151] wl_shm@6.format(808665688)
[1617426.154] wl_shm@6.format(942948929)
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
fish: Job 1, 'WAYLAND_DEBUG=1 ./target/debug/…' terminated by signal SIGABRT (Abort)
```

</details>

Neovide starts successfully using XWayland backend (`WINIT_UNIX_BACKEND=x11 ./target/debug/neovide`).

**Comment by barklan** [comment]
Might be duplicate of #1354

**Comment by Ernest1338** [comment]
As a workaround you can launch neovide while unsetting the WAYLAND_DISPLAY variable

**Comment by Cloudperry** [comment]
I was about to report this as a regression in Kwin, but Neovide didn't run on Sway either. It seems that the bug is in Neovide or winit then.

**Comment by MultisampledNight** [comment]
Weirdly enough I can't reproduce this on Sway version 1.7 and both git latest/0.8. Also there was no recent change to windowing stuff.

**Comment by Cloudperry** [comment]
I get the same error message on Sway as I get on Plasma. Are u using Sway 1.7 stable or git? If u are using the stable version that could explain the difference. Here are my versions of Sway and Neovide (all from Chaotic AUR):
```
~ ❯ paru -Qs neovide
local/neovide-git 0.8.0.r32.g7a3bf52-1
    No Nonsense Neovim Client in Rust
~ ❯ paru -Qs sway
local/sway-git r6938.49cef51e6-1
    Tiling Wayland compositor and replacement for the i3 window manager
~ ❯ paru -Qs wlroots
local/wlroots-git 0.16.0.r5589.29291cb47-1
    Modular Wayland compositor library (git version)
```
I don't really use Sway so maybe there's something I'm doing wrong with Sway. I haven't changed the default config of Sway and only have some very basic envvars in the startup desktop file. My Wayland and Wayland protocols versions are just the normal stable releases.

**Comment by Compizfox** [comment]
> Might be duplicate of #1354

It is, I forgot to mention this in my issue report but I'm also using kwin_wayland 5.25. I'll close my issue since this one is more active now.

**Comment by barklan** [comment]
It seems the issue does not exist when using updated winit+glutin. Maybe because of newer version of wayland-protocols libraray, since [smithay/client-toolkit](https://github.com/smithay/client-toolkit) (dependancy of winit) uses unstable wayland protocols?

I've managed to get Neovide working [here](https://github.com/barklan/neovide/tree/barklan) using [maroider](https://github.com/maroider)'s fork of winit ([new keyboard api for linux branch](https://github.com/rust-windowing/winit/pull/1932)).
Although my fork of Neovide probably works only on Linux+Wayland as new keyboard PR's for winit are still outstanding. And I had to remove IME input in my fork since there was some breaking change in API (likely [this commit](https://github.com/neovide/winit/commit/f04fa5d54f4ec10cdb6d084deeb79d3e6d27ae67)).

**Comment by ErikReider** [comment]
Launching in XWayland is a workaround for now `WINIT_UNIX_BACKEND=x11 neovide --nofork`

**Comment by MultisampledNight** [comment]
It's not a real workaround. Xwayland has issues with HiDPI on sway and the sway developers refuse to fix it, through which every program which connects through X only gets `available_window_size / hidpi_scale` as window size, then just scaling up, ending up pixelated. Also there's #1278 which I'm completely clueless about.

**Comment by WhyNotHugo** [comment]
Also an issue on swaywm (both latest release and master).

**Comment by WhyNotHugo** [comment]
As far as I can tell, the issue is in the fork of winit that's being used here.

Any chance that the changes on that fork can be rebased onto winit/master and eventually be upstreamed? Or have they been rejected by upstream?

**Comment by MultisampledNight** [comment]
We don't have any changes that aren't in a way upstream already. The only thing the fork really does is combining the 3 major platform PRs already upstream for a new keyboard API. The problem is that these PRs have partly not been touched any recently, some have fallen out-of-date completely and would need to be rebased by someone knowing platform internals, some have been recently rebased already. See the first bullet point in #1463 and following discussion.

**Comment by WhyNotHugo** [comment]
What does the new keyboard API bring to the table that's really necessary here? Is it possible to make due without it (keep in mind that, at this point, it works only on X11 but not on Wayland).

**Comment by WhyNotHugo** [comment]
(I did take a look at https://github.com/rust-windowing/winit/pull/1932/files, but it's not immediately obvious to me what's the new thing there that's needed for neovide)

**Comment by MultisampledNight** [comment]
It does work on Wayland already. And it's just that the old API was (or more to say, is) _majorly_ uncomfortable to work with, and you often need to map two events which technically occur at different points in code together in order to receive any meaningful information about actual character pressed + modifiers.

**Comment by ErikReider** [comment]
Works for me on Sway 1.7

**Comment by thomascft** [comment]
Are there any plans to merge upstream winit any time soon?

**Comment by tan-wei** [comment]
> 

This works as a workaround.

**Comment by WhyNotHugo** [comment]
> This works as a workaround.

What does?

**Comment by tan-wei** [comment]
> > This works as a workaround.
> 
> What does?


```
env -u WAYLAND_DISPLAY neovide
```

**Comment by mightyiam** [comment]
For me, both workarounds:

```
WINIT_UNIX_BACKEND=x11 neovide
```

And

```
env -u WAYLAND_DISPLAY neovide
```

succeed in launching neovide.

Yet, there's a different problem, then. If the window loses focus, I can't seem to get it to accept key strokes again by simple focusing it. I'm using swaywm, by the way. If I move the mouse over it, it does start accepting key strokes.

**Comment by pupbrained** [comment]
> For me, both workarounds:
> 
> ```
> WINIT_UNIX_BACKEND=x11 neovide
> ```
> 
> And
> 
> ```
> env -u WAYLAND_DISPLAY neovide
> ```
> 
> succeed in launching neovide.
> 
> Yet, there's a different problem, then. If the window loses focus, I can't seem to get it to accept key strokes again by simple focusing it. I'm using swaywm, by the way. If I move the mouse over it, it does start accepting key strokes.
> 
> 

Same exact issue here, on Hyprland

**Comment by chilipepperhott** [comment]
It looks like barklan's fork works perfectly on Sway, but on Hyprland it still crashes on startup.

**Comment by REmerald** [comment]
Stopped working on sway after upgrading `wlroots (0.15.1-6 -> 0.16.1-2)` and `sway (1:1.7-10 -> 1:1.8-3)` on arch linux.

Output error is the same.

**Comment by itaranto** [comment]
> Stopped working on sway after upgrading `wlroots (0.15.1-6 -> 0.16.1-2)` and `sway (1:1.7-10 -> 1:1.8-3)` on arch linux.
> 
> Output error is the same.
> 
> UPD: I noticed also `libxkbcommon (1.4.1-2 -> 1.5.0-1)` and `libxkbcommon-x11 (1.4.1-2 -> 1.5.0-1)` were upgraded. Could they be an issue?

This is exactly what happened to me, it stopped working after updating `wlroots`.

**Comment by itaranto** [comment]
I created a specific sway/wlroots issue here: https://github.com/neovide/neovide/issues/1724

**Comment by WhyNotHugo** [comment]
There's no need for a separate ticket for wlroots. The root cause is the same and opening duplicate tickets won't help.

The main issue is that neovide uses forks of older versions of libraries which has issues on most wayland implementations.

See also: https://github.com/neovide/neovide/issues/1588

**Comment by itaranto** [comment]
> There's no need for a separate ticket for wlroots. The root cause is the same and opening duplicate tickets won't help. The main issue is that neovide uses forks of older versions of libraries which has issues on most wayland implementations. See also: #1588

Sorry about that, I was thinking that maybe the root cause could be different.

You can close it as duplicate if you with.

**Comment by REmerald** [comment]
> The main issue is that neovide uses forks of older versions of libraries which has issues on most wayland implementations.

And that's because the devs have been waiting for https://github.com/rust-windowing/winit/pull/1932 and https://github.com/rust-windowing/winit/pull/1890 to merge.  
Noticing that pull requests are now almost 2 years old makes me sad...  
Is it ever going to happen? Maybe move from winit to e.g. gtk?

**Comment by WhyNotHugo** [comment]
Perhaps it's best to use latest upstream `winit`, and adapt to the new API when (if?) that is merged?

I know the new API has better ergonomics, but I'd rather have something using a less polished API that works, rather than something with a cleaner API that crashes at startup.

So far this crashes on `swaywm`, `hyperland` and `KDE`. Is there any wayland compositor where it does run?

**Comment by tomshoo** [comment]
> So far this crashes on swaywm, hyperland and KDE. Is there any wayland compositor where it does run?

There is GNOME, but then there is the other issue of weird title bar, [#728](https://github.com/neovide/neovide/issues/728).

**Comment by insonifi** [comment]
> There is GNOME, but then there is the other issue of weird title bar, [#728](https://github.com/neovide/neovide/issues/728), which is again related to winit.

I switched to GNOME a few weeks ago, still have the same issue.

**Comment by CarloCattano** [comment]
Still present. If starting it up with ```WINIT_UNIX_BACKEND=x11 neovide``` it displays on a tiny rectangle and full screen is not fully functional.
Any workarounds ? 
Im on arch and hyprland

**Comment by MultisampledNight** [comment]
Not a workaround (well, semi) but I have the following suggestion to make:

- The winit PR https://github.com/rust-windowing/winit/pull/1932 (from now on referred to as the "linux PR") provides the "new" keyboard API for Linux in winit, as required by Neovide. Only problems are that it uses wayland-client 0.29 (the newest is 0.30), which doesn't seem to work on Hyprland (https://github.com/neovide/neovide/issues/1356#issuecomment-1371084992), and that it is out of sync with the [other new keyboard API PRs](https://github.com/rust-windowing/winit/pulls?q=is%3Apr+in%3Atitle+new+keyboard+api).
- Completely insane, but we could improve this by
  - forking the linux PR
  - upgrading it to wayland-client 0.30 and the latest smithay-client-toolkit version
  - creating a PR at the winit repo with the linux PR as target
  - pulling in that upgraded branch to a new dependency `winit_linux`/`winit_wayland`
  - using that dependency only on Wayland as a replacement for winit.

The end result of this would mean 2 different winits in our dependency tree, but at least we can handle Wayland upgrades independently of the other platforms then, and other platforms are very unlikely to make breaking changes.

**Comment by WhyNotHugo** [comment]
> Still present. If starting it up with WINIT_UNIX_BACKEND=x11 neovide it displays on a tiny rectangle and full screen is not fully functional.

This sounds like a separate issue (the issue being discussed here is when using the wayland backend, but you're explicitly specifying  different one). I suggest opening a separate ticket with all the relevant details.

**Comment by thomascft** [comment]
> So far this crashes on `swaywm`, `hyperland` and `KDE`. Is there any wayland compositor where it does run?

I've had success on river and I think wayfire as well.

**Comment by mightyiam** [comment]
I love neovide. I've been using it for a few months and now I can't seem to use it due to this bug :cry: .

**Comment by MultisampledNight** [comment]
Fwiw now we're having eyes on https://github.com/rust-windowing/winit/pull/2662 instead of the aforementioned two PRs. The winit maintainers are not quite finished on negotiating their API, but the PR is moving _very_ fast.

**Comment by williamspatrick** [comment]
> Fwiw now we're having eyes on [rust-windowing/winit#2662](https://github.com/rust-windowing/winit/pull/2662) instead of the aforementioned two PRs. The winit maintainers are not quite finished on negotiating their API, but the PR is moving _very_ fast.

Is there more to it than just winit?  I changed the winit dependency to point at this PR, rebuilt, and still have the same issues.

```
winit = { git = "https://github.com/rust-windowing/winit", branch = "new-keyboard-v3" }
```

**Comment by williamspatrick** [comment]
> Is there more to it than just winit? I changed the winit dependency to point at this PR, rebuilt, and still have the same issues.
> 
> ```
> winit = { git = "https://github.com/rust-windowing/winit", branch = "new-keyboard-v3" }
> ```

I guess the glutin dependency also needs to be updated.

**Comment by MultisampledNight** [comment]
The whole API is different, except for making changes in Neovide itself there's nothing possible to do from a user perspective.

**Comment by williamspatrick** [comment]
> It seems the issue does not exist when using updated winit+glutin. Maybe because of newer version of wayland-protocols libraray, since [smithay/client-toolkit](https://github.com/smithay/client-toolkit) (dependancy of winit) uses unstable wayland protocols?
> 
> I've managed to get Neovide working [here](https://github.com/barklan/neovide/tree/barklan) using [maroider](https://github.com/maroider)'s fork of winit ([new keyboard api for linux branch](https://github.com/rust-windowing/winit/pull/1932)). Although my fork of Neovide probably works only on Linux+Wayland as new keyboard PR's for winit are still outstanding. And I had to remove IME input in my fork since there was some breaking change in API (likely [this commit](https://github.com/neovide/winit/commit/f04fa5d54f4ec10cdb6d084deeb79d3e6d27ae67)).

Awesome.  Thanks.  I've managed to rebase this content onto the latest in main and I can now run under Sway.

https://github.com/williamspatrick/neovide/commit/677e87e887bc14544ca6156907666a5739f5a361

**Comment by mightyiam** [comment]
@williamspatrick more motivated than I am :clap: .

**Comment by chilipepperhott** [comment]
> [williamspatrick@677e87e](https://github.com/williamspatrick/neovide/commit/677e87e887bc14544ca6156907666a5739f5a361)

Can confirm this works on Hyprland

**Comment by shaunsingh** [comment]
I'd like to wait around a bit until the new keyboard api lands and then update neovide to support the upstream version of winit, I'm not sure what other changes our fork has but we can upstream them if nessecary. This should fix the above issues (and let us publish to crates.io, finally :))

I'd rather not depend on a PR in main, mainly because its a moving target and we *might* need to keep up with it. Stay tuned, just a bit longer!

**Comment by Tmpod** [comment]
> https://github.com/williamspatrick/neovide/commit/677e87e887bc14544ca6156907666a5739f5a361

Unfortunately, doesn't seem to work on KWin Wayland. I compiled the latest from your fork in release mode and it would only launch under XWayland. :smiling_face_with_tear:

**Comment by Ciel-MC** [comment]
Just updated with neovide-git from the AUR, doesn't launch for me either, also on Kwin Wayland :c

**Comment by shaunsingh** [comment]
This will eventually be fixed by https://github.com/neovide/neovide/pull/1789, in combination with https://github.com/neovide/neovide/pull/1797

(PR 1789 doesn't build on linux, though PR 1797 will fix that - I haven't tested it yet though)

**Comment by Yesterday17** [comment]
I managed to make it work in #1813, which depends on changes on both winit(https://github.com/neovide/winit/pull/11) and glutin(https://github.com/neovide/glutin/pull/3) side.

Try [this branch](https://github.com/Yesterday17/neovide/tree/new-keyboard-v3-dep) if you want a working version on Wayland :eyes:

**Comment by Yesterday17** [comment]
> I had to use --novsync for it to launch.

I've also encountered this problem. But I do not have any experience on rendering to dig further. What I found is that all egl configs on my desktop seems to have both `MIN_SWAP_INTERVAL = 0` and `MAX_SWAP_INTERVAL = 0`, but `vsync` requires this value to be `1`, which caused the panic.

> Secondly, repeatable key input doesn't seem to work.

Could you please explain it in detail?

---
In addition, I've implemented basic IME support referencing the `[ime-position]` branch. Here's my part of my configuration:

```lua
if vim.g.neovide then
  vim.g.neovide_ime_enabled = false
  vim.g.neovide_ime_at_bottom = true
  vim.api.nvim_create_autocmd("ModeChanged", {
    pattern = "i*:*",
    callback = function() vim.g.neovide_ime_enabled = false end,
  })
  vim.api.nvim_create_autocmd("ModeChanged", {
    pattern = "*:i*",
    callback = function() vim.g.neovide_ime_enabled = true end,
  })
end
```

[ime-position]: https://github.com/neovide/neovide/tree/ime-position

**Comment by huge-pancake** [comment]
Still can not run a native wayland Neovide on Hyprland.

It is true that I can run Neovide under Xwayland, but the keys are delayed

**Comment by DashieTM** [comment]
Curious, what version of hyprland are you running @alerque ?
personally it still crashes with the wl_shm code 0. (also running hyprland, tested on hyprland version 0.23 and git)

**Comment by alerque** [comment]
Hyprland v0.23.0 here.

Also even though I saved my dotfiles at the point I figured out how to get the key delay to go away, it is back and I can't figure out a combination that works again. Neovide runs fine. Without `--multigrid` noice works in it, with `--multigrid` it all goes haywire. Neither with or without `--async` work to make the key delay go away.

**Comment by huge-pancake** [comment]
@alerque the original version Neovide in Archlinux on XWayland works well (with --novsync for no key delay), but it still can't run without X.

(I just don't like running X in Wayland)

I'm trying the branch you mentioned.

**Comment by DashieTM** [comment]
@huge-pancake you made the same mistake as I did, you used main, that doesn't work.
However, can you check to see if the key "k" gets repeated when you try again with the new-keyboard-v3-dep branch ?

**Comment by huge-pancake** [comment]
@DashieTM Thanks a lot! I didn't notice that. It works now.

**Comment by tom-kuca** [comment]
@DashieTM I tried it, `k` does not repeat for me. Other keys do, in neovim, `k` repeats.

* neovide 1eb12d29fde327379a4de6a32d2f483506eede75 (new-keyboard-v3-dep branch, ` ./target/debug/neovide -- --clean`)
* sway version 1.8.1, hyprland 0.23.0
* NVIM v0.9.0

Regarding noice, it works without `--multigrid`. With `--multigrid`, it crashes with
```
  ❯ RUST_BACKTRACE=1 ./target/debug/neovide  --multigrid
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format [1, [205, 3, 232]]
Neovide panicked with the message 'Could not parse event from neovim: invalid u64 format [1, [205, 3, 232]]'. (File: src/error_handling.rs; Line: 5, Column: 5)
 ```

Backtrace: https://gist.github.com/tom-kuca/0dfd64b2582178a2e45a3be63c3858ae

With full configuration, I noticed an issue with slow cursor movement on one of the files. When I hold `j`, it moves about 10 lines, then the cursor gets stuck for about 300 ms. Sometimes I can see two black boxes representing the cursor. It happens even in the middle of the screen when there is no scrolling. It's smooth if I disable treesitter `TSDisable highlight` or in neovim or with `WINIT_UNIX_BACKEND=x11 `. 
I suspect that rendering is slower with wayland version and here is the case when it's observable. It might not be related to this issue.

**Comment by Yesterday17** [comment]
> However, can you check to see if the key "k" gets repeated when you try again with the new-keyboard-v3-dep branch ?

I managed to fix this issue in [19d9aaf](https://github.com/Yesterday17/winit/commit/19d9aaf11d881981649cc6c67cf6db401866a4a2). (But I do not know what the '+ 8' actually means :eyes:)

Also, I made `new-keyboard-v3-dep` branch default in my fork so that `cargo install --git` works out of the box.

**Comment by CarloCattano** [comment]
the only way I have to run it on wayland (Hyprland)
```
alias xw='env -u WAYLAND_DISPLAY'
alias nv="xw neovide --multigrid"
```

**Comment by alerque** [comment]
I think that means you are not running it under Wayland at all but Xwayland. Also since you didn't identify what version of neovide you are even trying (a tagged version? Head? the fork that we've been talking about here that works for some of us?) that doesn't help anybody too much. It's known that the current released versions only work on Xwayland.

**Comment by fdev31** [comment]
Hi, using Hyprland here...
It is crashing on start:
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
zsh: IOT instruction (core dumped)  neovide --nofork --log neo.log --novsync -- --clean
```

The trick to remove `WAYLAND_DISPLAY` works.

**Comment by WhyNotHugo** [comment]
> The trick to remove WAYLAND_DISPLAY works.

This just makes it run via XWayland instead of Wayland. Running on Xorg has never been broken, this issue is Wayland-specific.

**Comment by Hubro** [comment]
> I managed to make it work in #1813, which depends on changes on both winit([neovide/winit#11](https://github.com/neovide/winit/pull/11)) and glutin([neovide/glutin#3](https://github.com/neovide/glutin/pull/3)) side.
> 
> Try [this branch](https://github.com/Yesterday17/neovide/tree/new-keyboard-v3-dep) if you want a working version on Wayland eyes

Hey wtf, your branch works! After a few hours of usage I haven't run into any issues with it either.

Are the fixes you made something that could be merged? Or does it break other things?

It's a bit sad that Wayland support has been broken for almost a year at this point :confused:

**Comment by fredizzimo** [comment]
@patatahooligan, We have had a PR for that open for some time already here https://github.com/neovide/neovide/pull/1789 and we updated it to use the Winit master yesterday

At least for me Wayland works properly with that as long as you use it natively so don't use `WINIT_UNIX_BACKEND=x11`. You might also need to start Neovide with `--nosrgb` if the colors are too dark.

If you want to feel more adventurous you can use this branch instead https://github.com/neovide/neovide/pull/1870, which not only includes the winit changes but also completely rewrites the rendering loop to make the scrolling almost completely smooth with `--multigrid`

**Comment by TenEXP** [comment]
With commit [f412399](https://github.com/neovide/neovide/commit/f412399676c83ea670cd22745b850dad9ee210a0), neovide runs perfectly, at least for me on Hyprland. I believe this issue is now resolved and should be marked as closed.

**Comment by fredizzimo** [comment]
Yes, let's close this. There's another issue for the snaps with wayland https://github.com/neovide/neovide/issues/1060, which might actually be the same issue, but that one will remain open until that is tested.

**Comment by bitmage** [comment]
I'm noticing that with this workaround:

```
env -u WAYLAND_DISPLAY neovide
```

The clipboard integration fails to work properly, because as documented in `:h clipboard`:

```
The presence of a working clipboard tool implicitly enables the '+' and '*'
registers. Nvim looks for these clipboard tools, in order of priority:

  - |g:clipboard|
  - pbcopy, pbpaste (macOS)
  - wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
  - waycopy, waypaste (if $WAYLAND_DISPLAY is set)
```

Because $WAYLAND_DISPLAY is not set, the clipboard commands don't get wired up properly.

1. How would I install the version https://github.com/neovide/neovide/commit/f412399676c83ea670cd22745b850dad9ee210a0?  Neovide is currently installed via `pacman` for me on Manjaro.
2. Is there a way to work around the $WAYLAND_DISPLAY variable not being set, and manually wire up the clipboard?  I tried setting my leader keys for `y` and `p` manually, but I'm apparently not doing that correctly.  An example would help if anyone is willing to provide.

**Comment by fredizzimo** [comment]
@bitmage, don't use any workaround, `WAYLAND_DISPLAY` should remain as it is set by the system.

For installing you could either build the master from source, https://neovide.dev/installation.html#linux-source. But since you are on Manjaro, you could probably use this from aur https://aur.archlinux.org/packages/neovide-git version. The third option is to download it from the build artifacts https://github.com/neovide/neovide/actions/runs/5272313380
