### ISSUE TITLE
Poor performance after update to 0.10.3

### ISSUE THREAD

**Issue by fecet** [neovide/neovide#1634]
The scroll become very slow after update to 0.10.3, I also tried 0.10.2, the speed looks the same.

0.10.1 works well before.

**Comment by MultisampledNight** [comment]
Thanks for reporting! I haven't been able to experience that myself, but my system is also pretty chonk-y.

I believe the performance hit came from the recent smooth scrolling fixes, could you both try [the commit before that fix](https://github.com/neovide/neovide/actions/runs/2897737596) and [the commit after that fix](https://github.com/neovide/neovide/actions/runs/2897828197)?

**Comment by fecet** [comment]
I modify PKGBUILD from https://aur.archlinux.org/neovide-git.git, both commits work fine.

**Comment by MultisampledNight** [comment]
So the hit didn't come from there. Since you seem to have access to the repo locally and can build from source, would it be possible for you to `git bisect` from 0.10.1 to HEAD to find out which commit introduced the hit?

**Comment by fecet** [comment]
OK I will check it later

**Comment by fecet** [comment]
Here is what I found
```
❯ git bisect bad
d253648e8a97f1e01c3fef0c80a88651f344d880 is the first bad commit
commit d253648e8a97f1e01c3fef0c80a88651f344d880
Author: multisn8 <contact@multisamplednight.com>
Date:   Sat Oct 8 13:37:12 2022 +0200

    Make vsync configurable (#1523)

    Tries to request vsync first, and retries window creation without if it fails.

 src/cmd_line.rs                        |  4 ++++
 src/window/mod.rs                      | 25 +++++++++++++++++++++----
 website/docs/command-line-reference.md |  8 ++++++++
 3 files changed, 33 insertions(+), 4 deletions(-)
```

**Comment by MultisampledNight** [comment]
Thank you! This is very interesting. I believe Neovide's sub-par frame pacing interferes with the vsync requested on the window.

For now, you can work around it by passing `--novsync` to Neovide, I'll investigate if it's worth removing it later on. Maybe after #1312 enabling vsync has real effect.

**Comment by fecet** [comment]
I note #1312 mention something about frame rate, so I investigate it further, I have set 
```
let g:neovide_refresh_rate = 138
```
in init, if I set it to 60, neovide works fine even without `novsync`. If I do not change, 
anything, i.e., refresh_rate=138 and start neovide as usual, the profiler fixed at 60fps,
with `novsync`, the profiler is 138fps. 

Does the profiler report the true frame rate? As the profiler still report 138fps on my laptop with a 60fps screen.

**Comment by MultisampledNight** [comment]
The profiler reports at which rate frames are rendered in Neovide, not when they're presented. Vsync says "ok, for every frame rendered, when propagating it you get blocked for so long that the display actually presents that frame". `--novsync` disables that.

**Comment by fredizzimo** [comment]
I have a lot of fixes related to this in https://github.com/fredizzimo/neovide/tree/fsundvik/improve-performance. 

But it’s still not quite ready for for a pull request. If try it right now, you will need the`—noidle` flag. I think that the vsync flag happens to be forced off in the version I have pushed currently, so you probably get an fps of at least several hundreds, I get around 2000. 

But no matter how high the frame rate is, It will never be smooth without vsync. So I’m working on getting that working correctly. The biggest issue is that there are some random frame drops that I haven’t quite figured out yet.

The next step is to integrate https://github.com/wolfpld/tracy, so that I’m properly able to figure out what happens during those spikes.

**Comment by xbladesub** [comment]
same, very very slow on 10.0.3... Upgraded from 10.0.1

**Comment by sid-6581** [comment]
I'm seeing the same slow performance on my laptop with a hybrid Intel/NVidia GPU. I'm not sure which part is used for rendering Neovide, but I'd suspect the Intel. It takes seconds to respond to any input. However, on my desktop with an NVidia 3090, it's still fast. It has a 120hz screen as opposed to the laptop's 60hz screen, and I have Neovide's refresh rate set to 120 on both machines. When I dropped the Neovide refresh rate on the laptop down to 60 fps to match the panel's refresh rate, speed seemed to go back to normal.

**Comment by fecet** [comment]
> Neovide's

that is exactly what i experienced and --novsync works as a temporary workaround

**Comment by fecet** [comment]
> I'm seeing the same slow performance on my laptop with a hybrid Intel/NVidia GPU. I'm not sure which part is used for rendering Neovide, but I'd suspect the Intel. It takes seconds to respond to any input. However, on my desktop with an NVidia 3090, it's still fast. It has a 120hz screen as opposed to the laptop's 60hz screen, and I have Neovide's refresh rate set to 120 on both machines. When I dropped the Neovide refresh rate on the laptop down to 60 fps to match the panel's refresh rate, speed seemed to go back to normal.

that is exactly what i experienced and --novsync works as a temporary workaround

**Comment by jggc** [comment]
On archlinux like some other folks using a 4k display that's limited to 30hz over HDMI plugged  from a dual GPU Laptop.

Using either one workaround fix it for me : 
 - `neovide --novsync`
 - `:let g:neovide_refresh_rate=30`

**Comment by Joarell** [comment]
Hi guys!
I have been the same issue.
I don't know if you have checked this before, but when you turn off the `relativenumber`, all works fine on this version of Neovide.
However, I agree it's not a good experience on Vim/Neovim/Neovie, when we are coding.

Finally, I'd apologize with you because I don't have a glue how it affects the Neovide performance, so I can't offer any help to this issue. But maybe it would be a good spot to do some investigation on.
Have you all a nice day!

**Comment by alerque** [comment]
I don't have `relativenumber` enabled and also have major performance problems. I came here today to make sure it was reported (I'm also the Arch Linux packager). I tried the Git HEAD build as well with the same issues.

Using `--novsync` seems to bring back the spritely response time to input.

Also just a note this issue mentions smooth scroll and such, but the lag I was seeing happens in buffers with no scroll or complex syntax or anything, just a two line plain text file. The lag is so noticeable when typing that I have to close my eyes to input text otherwise I goof it up because the display lag is so far behind.

If there is anything needed to help debug this or isolate it to certain system conditions let me know.

**Comment by fredizzimo** [comment]
I think this should fix the performance issues https://github.com/neovide/neovide/pull/1870

**Comment by fecet** [comment]
> I don't have `relativenumber` enabled and also have major performance problems. I came here today to make sure it was reported (I'm also the Arch Linux packager). I tried the Git HEAD build as well with the same issues.
> 
> Using `--novsync` seems to bring back the spritely response time to input.
> 
> Also just a note this issue mentions smooth scroll and such, but the lag I was seeing happens in buffers with no scroll or complex syntax or anything, just a two line plain text file. The lag is so noticeable when typing that I have to close my eyes to input text otherwise I goof it up because the display lag is so far behind.
> 
> If there is anything needed to help debug this or isolate it to certain system conditions let me know.

I also notice performance drop if `relativenumber` or `cursorcolumn` are enabled, semantic tokens and treesitter cloud also lead to bad performance under `neovide-git`. And I just tried #1870, it seems works great and faster than neovim in alacritty and kitty.
