### ISSUE TITLE
<A-i> does not work 

### ISSUE THREAD

**Issue by saikete** [neovide/neovide#1867]
**Describe the bug**
<A-i> does not work and has set vim.g.neovide_input_macos_alt_is_meta=true

**To Reproduce**
1. clone NvChad nvim-config
2. install, and run
3. In the terminal, <A-i> can work normally, but in neovide, it cannot work normally, <A-h><A-v> can call out the terminal normally

**Expected behavior**
<A-i> You can call out the terminal normally in neovidide

**Screenshots**
<img width="559" alt="image" src="https://github.com/neovide/neovide/assets/45237450/79a62fff-ea9e-419c-b17a-e4e8da357a7c">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 13.3.1]
 - Neovide Version [0.10.4]
 - Neovim Version [0.9.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
(to large)

**Additional context**

**Comment by saikete** [comment]
and my keyboard is hhkb

**Comment by fredizzimo** [comment]
Could you try the latest master version, the keyboard handling was changed a lot here https://github.com/neovide/neovide/pull/1789

**Comment by saikete** [comment]
I am using version 0.10.4 now, the main branch seems to be the latest version, right?

**Comment by saikete** [comment]
I am using version 0.10.4 now, the main branch seems to be the latest version, right?

**Comment by saikete** [comment]
And I have other problems when using the Chinese input method

**Comment by saikete** [comment]
When backspace deletes the candidates in the input box, it will be deleted together with the following characters in insert mode

**Comment by saikete** [comment]
Yes, it is true that <A-i> works, but <A-h> and <A-v> do not work,,

**Comment by saikete** [comment]
Yes, it is true that <A-i> works, but <A-h> and <A-v> do not work，，
Also, I did some configuration to switch the input method when I was editing, it seems that it is currently asking for permission, but I have checked the confirmation
<img width="806" alt="image" src="https://github.com/neovide/neovide/assets/45237450/b4d828f7-e60d-449a-aefe-88e81260ca29">
<img width="1080" alt="image" src="https://github.com/neovide/neovide/assets/45237450/38a1d609-7c6b-416e-9fdb-0c11059419fa">

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.

**Comment by saikete** [comment]
<img width="709" alt="image" src="https://github.com/neovide/neovide/assets/45237450/ed1f40f2-c848-45c0-8abc-c2368665806f">
I pulled the code of the new main branch, but the problem I described is still not resolved,,,
