### ISSUE TITLE
Neovide doesn't close until after clipboard has been changed externally

### ISSUE THREAD

**Issue by isovector** [neovide/neovide#2003]
**Describe the bug**

After yanking to the unnamedplus clipboard, neovide hangs on exit until some other program changes the clipboard.

**To Reproduce**

Given a minimal config, `~/.config/nvim/init.vim`:

```viml
autocmd!
set clipboard+=unnamedplus
```

then start neovide. Type:

```
yy:q!<CR>
```

Neovide will now hang, refusing to exit. It will immediately quit after copying to the clipboard from some other application.

**Expected behavior**

Neovide should not hang until the clipboard changes.

**Desktop (please complete the following information):**
 - OS: Linux 6.1.38-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jul  5 23:49:30 UTC 2023 x86_64 GNU/Linux
 - Neovide Version 0.11.1
 - Neovim Version v0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12477151/neovide_rCURRENT.log)

**Additional context**

Both lines of the config are necessary.

**Comment by fredizzimo** [comment]
Can you test this with terminal mode Neovim? Neovide itself should use the default Neovim clipboard integration unless you use wsl or a tcp connection to Neovim.

More specifically it should use `wl-paste` on Wayland, which can hang in certain situations, https://github.com/neovim/neovim/issues/24470.

**Comment by fredizzimo** [comment]
You could try to disable Neovide`s clipboard, although it should already be disabled.

vim: `let g:neovide_no_custom_clipboard = v:true`
lua: `vim.g.neovide_no_custom_clipboard = true`

Are you on Wayland or X11, and which desktop environment / window manager? We need to know which clipboard provider is used https://github.com/neovim/neovim/blob/b2c3e9c72ef12a5bc276dec78cdc8dfbd2f5a24b/runtime/autoload/provider/clipboard.vim#L69

And if that is running, blocking the exit of the process. Can you check that with `ps all`?

**Comment by isovector** [comment]
Interestingly, `xclip` isn't running on a fresh open of neovide, but does start immediately when I yank. Furthermore, it's in that same `Ss` status as soon as I yank anything (before I go to quit neovide.)

Running `nvim` reports the same clipboard, and also starts the same `xclip` process, but doesn't wait for `xclip` to close before exiting.

**Comment by isovector** [comment]
Installing `xsel` and ensuring the clipboard provider reports it also doesn't fix the issue.

**Comment by fredizzimo** [comment]
Hm. I'm not sure what's going on here. It's Neovim that launches the clipboard and is supposed to close it, but for some reason that does not happen. 

I'm also not able to reproduce it myself. So it's hard to debug. But does killing `xclip` let Neovide quite normally?

**Comment by isovector** [comment]
Killing `xclip` does indeed allow neovide to close normally. Happy to provide anything you might need to help debug!

**Comment by fredizzimo** [comment]
Can you test with https://github.com/neovide/neovide/pull/2009. I changed our exit code slightly to properly wait for Neovim to exit before terminating. There's a small chance that it fixes the issue.

**Comment by Kethku** [comment]
Closing for lack of response. Feel free to reopen if issues continue

**Comment by damanis** [comment]
The problem started after [https://github.com/neovim/neovim/commit/1d16bba4d8b8b648d2dabd610924bcf3051a0f29](https://github.com/neovim/neovim/commit/1d16bba4d8b8b648d2dabd610924bcf3051a0f29).
It occurs then `vim.o.clipboard = [[unnamed]]` is configured (this is useful configuration).
Note, that `neovim-qt` has no problem with clipboard.

**Comment by vargad** [comment]
I have the same problem as @damanis. All these cause neovide to hang until other app copies anything to the clipboard:
- `set clipboard^=unnamed,unnamedplus`
- `set clipboard^=unnamed`
- `set clipboard^=unnamedplus`
It only hangs if I copy with neovide to the clipboard. nvim does not hang. After removing `set clipboard` neovide doesn't hang either.

**Comment by fredizzimo** [comment]
This is not a universal problem, so it's hard to fix.

I don't have this problem in either KDE, Gnome, Sway or Hyprland, which I have all used recently, all of them Wayland though, I don't remember the last time I used X11 other than just for quick testing.

Here is a link to some initial code inspection based analysis that I did in another issue https://github.com/neovide/neovide/issues/2166#issuecomment-1840162407, if someone that can repeat the problem wants to continue from there. Basically, I think there are a couple of problems with that Neovim commit, but we might be able to work around it and we can't really report an issue, until we have more details, than it just stopped working after that.

Additionally, based on the symptoms, the problem might have something to do with some specific clipboard manager installed on the system.

**Comment by vargad** [comment]
I'm using X with AwesomeWM with no clipboard manager. Thank you for the link, I'll see, if I can figure it out, since I can reproduce it very quickly.

**Comment by fredizzimo** [comment]
Does neovim-qt exit cleanly or, forcefully after 500ms of waiting?
https://github.com/equalsraf/neovim-qt/blob/f5c95b19512ad0e3662be32507adfca8e2401c13/src/gui/mainwindow.cpp#L235-L253

**Comment by damanis** [comment]
@fredizzimo 
The `neovim-qt` exits cleanly, it does not wait anything.
It is not clear for me yet, what exactly occurs. I see that after pressing `yank` `nvim` runs `/usr/bin/xsel --nodetach -i -p` (checked by `execsnoop-bpfcc`). This process stays running after `neovim-qt` exits too, but `neovim-qt` has no problem with it (may be it just ignores the `xsel`?).

**Comment by fredizzimo** [comment]
@damanis, I mean the code in neovim-qt waits a half second for neovim to quit and then gives up. We need to know if it exits because of the timeout or because the wait succeeded.

Our code has no such timeout, because it’s slightly dangerous to forcefully kill neovim. The shada data for example is written at the exit, and could get corrupted.

**Comment by damanis** [comment]
@fredizzimo 
I checked now - neovim-qt does not enter to `MainWindow::neovimGuiCloseRequest`.

**Comment by fredizzimo** [comment]
I managed to reproduce the issue now, and reported a neovim bug
* https://github.com/neovim/neovim/issues/26743

**Comment by damanis** [comment]
@fredizzimo 
I get different behavior on Ubuntu 20.04 and  22.04.
I reported this issue for Ubuntu 20.04, but I can't reproduce the problem on Ubuntu 22.04 (while in `goneovim` the behavior same on both Ubuntu). The versions of neovim and neovide (installed by `cargo install`) are same.
On Ubuntu 22.04, instead, another issue: `nvim` backend stays run after `neovide` exits. To reproduce:
- run `neovide .bashrc`
- yank some text
- exit from `neovide` — `nvim` process stays run.

**Comment by fredizzimo** [comment]
I still think that neovim-qt forcefully closes Neovim if it's not responding. The rpcrequest, vs notify does not apply here, since our own clipboard integration is not in use unless you specifically enable it, or uses remote connections.

I don't want to add that to Neovide though, unless we absolutely need to since it can cause other issues, including corruption of data. We need a fix on the Neovim side.

I don't know what the difference between the two ubuntu versions are, but the issue seem to be the same, neovim does not properly quit until the clipboard is closed, and should be fixed by the same fix.

**Comment by damanis** [comment]
@fredizzimo 
I tried you suggestion (close stderr , `call jobclose(jobid, 'stderr')`, for xsel) in [neovim issue](https://github.com/neovim/neovim/issues/26743) — it does not solve the problem.

**Comment by fredizzimo** [comment]
@damanis, did you also close stdout? Both needs to be closed. Also make sure that you are using xsel, and not xclip

**Comment by damanis** [comment]
@fredizzimo 
There are changes I made in neovim tree, then compile and install.
```
diff --git a/runtime/autoload/provider/clipboard.vim b/runtime/autoload/provider/clipboard.vim
index 05f6bdb87..7a82b838c 100644
--- a/runtime/autoload/provider/clipboard.vim
+++ b/runtime/autoload/provider/clipboard.vim
@@ -216,9 +216,10 @@ function! s:clipboard.set(lines, regtype, reg) abort
     call jobsend(jobid, a:lines)
     call jobclose(jobid, 'stdin')
     " xclip does not close stdout when receiving input via stdin
-    if selection.argv[0] ==# 'xclip'
+    " if selection.argv[0] ==# 'xclip'
       call jobclose(jobid, 'stdout')
-    endif
+      call jobclose(jobid, 'stderr')
+    " endif
     let selection.owner = jobid
     let ret = 1
   else
```

**Comment by fredizzimo** [comment]
Strange, it worked for me, but I'm not sure if I tested the workaround for xsel, only xclip, so there could be a difference there.

Are you, sure that you are using the correct nvim binary that you compiled yourself?

**Comment by damanis** [comment]
> Are you, sure that you are using the correct nvim binary that you compiled yourself?

Yes, I removed nvim.appimage before testing.

**Comment by fredizzimo** [comment]
This might "fix" the issue due to neovide no longer waiting for neovim to exit

* https://github.com/neovide/neovide/pull/2265

But it might cause an almost equally bad issue of leaving Neovim running in the background after neovide exits.Perhaps even leaving `swp` files open.

But I'm not sure,  so it would be great if someone could test and see what happens as I can't do it myself now.

**Comment by damanis** [comment]
I compiled the patch #2265 on Ubuntu 20.04.
The clipoboard (with `xsel`), works properly, I did not see problem yet.
`Neovim` process stays in background after `neovide` exits, but it self stopped after few time.

**Comment by fredizzimo** [comment]
This is fixed in Neovim 0.10.0 and since our new 0.13.0 release requires that, I'm closing this issue.

**Comment by damanis** [comment]
Great news!
