### ISSUE TITLE
Random freeze

### ISSUE THREAD

**Issue by idelice** [neovide/neovide#2384]
**Describe the bug**
Neovide freezes spontaneously and forces me to restart it. I have no idea how it happens, but it happens in every scenario; writing code, using commands, opening plugins like telescope and so on therefor I can't pinpoint _exactly_ when it happens. Only that it happens.

**To Reproduce**
1. Use the LazyVim distro
2. Do your stuff like I've described above.
3. Boom.. sudden freeze. You have to restart neovide now

**Expected behavior**
I expect it to not freeze.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Sonoma 14.3
 - Neovide Version 0.12.2
 - Neovim Version 0.9.5

**Comment by pidgeon777** [comment]
I have to say that for a few weeks I've been also experiencing some random freezes using Neovide.

Using another Neovim GUI, [Nvy](https://github.com/RMichelsen/Nvy), this freezes doesn't occur.

So, I suppose it is not the `nvim.exe` process which crashes, but there is a bug related to Neovide itself.

I will run Neovide with the `--log` option, but then what should I expect as output after the crash? So that I can also investigate.

**Comment by pidgeon777** [comment]
I downloaded the latest Neovim nightly version, I'll check if the issue still persists.

**Comment by pidgeon777** [comment]
Unfortunately the issue seems to occur again, especially when saving buffers.

How could I debug this issue?

**Comment by axelhj** [comment]
I saw in another issue that there is some fix merged in Neovim just about a week ago, specifically for random Neovide freezing issues. I can't find the id though.

**Comment by Delice0** [comment]
Seems I can **continuously** reproduce this behavior by doing the following in order:

1. go to block visual mode (SHIFT + v)
2. go to end of file (SHIFT + $)
3. do SHIFT + % to go to end bracket
4. delete (dd)

I tried this **10 times now**, and the app froze **_every single time_**

**Comment by axelhj** [comment]
Hi! I've downloaded and build Neovim from source; `v0.10.0-dev-41fb98d` and the issue was not resolved. I run ToggleTerm with three side-by-side panes quite often and it freezes roughly once per day in this scenario. So probably this is more appropriate in https://github.com/neovide/neovide/issues/2166 but just to say that it might be related with what @pidgeon777 described.

**Comment by pidgeon777** [comment]
Unfortunately those random freezes still occur, only when using `Neovide`. This for example doesn't happen when using other GUIs such as [Nvy](https://github.com/RMichelsen/Nvy).

**Comment by pidgeon777** [comment]
I updated to the latest `nvim` nightly release, but these random freezes still occur. Maybe it's because of the `noice` plugin in the `LazyVim` distribution?

However, these crashes don't occur in `Nvy`.

I think I will have to stick with the latter, as `Neovide` is currently unusable in my setup, which is very unfortunate.

**Comment by axelhj** [comment]
I would like to add that I see the freezes with WezTerm too, albeit alightly less frequently. Seems when I exit processes in toggleterm this happens but less often than every 10 times.

**Comment by Delice0** [comment]
**Update**

It also freezes when working on java files and triggering LSP code actions like importing and renaming etc.

**Comment by pidgeon777** [comment]
I have no idea how those random freezes could be debugged, both `Neovim` and `nvim` side.

If someone has any idea, please let me know.

**Comment by axelhj** [comment]
I don't have time to debug it myself, but if you're able to get set up it might help my case a bit aswell; these points are pretty much where I would start:

Debugging is a little bit different if the Nvim process itself has crashed; in this case you could get a core-dump on OSX near automatically as described [here](https://neovim.io/doc/user/dev_tools.html.)  (I myself am not on macOS so have no more info than that).

A simple way to get source level debugging setup would be to install CLion Community if you're elegible and get setup for debugging the Nvim process itself (or another IDE, Neovim+nvim-gdb would work to debug itself too for that matter). That way you could probably attach to the Nvim process (it is running as a subprocess to Neovide on my computer anyway). You could clone the Nvim source and attach to Nvim after launching it and wait for the freeze. When the freeze occurs, you would be able to see if/where in the code Nvim did lockup/freeze. I should note that you don't need to have the source checked out or even CLion installed to debug a process with GDB but to me it seems the more simple path.

Debugging the Neovide program might require some Rust tooling. Neovide.dev has some steps. I couldn't say if this would be a better starting point than debugging Nvim itself.

Additionally, it might be possible to get valuable information simply by adding more logging. Using the [-V](https://neovim.io/doc/user/starting.html#-V) option should cause Neovim to produce more logs. I will try this myself.

Hope that helps, and that it's not too much.

**Comment by fredizzimo** [comment]
The easiest way to debug Neovide is probably with Visual Studio code, settup up DAP in neovide is a bit trickier, and I don't even have it setup myself, so I can't give proper instructions, but you need:
* https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb

And then the following launch configuration
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "lldb",
            "request": "launch",
            "args": [],
            "cargo": {
                "args": ["build"]
            }
        },
    ]
}
```
This will build the debug configuration, so it's slower than normal, but it should be easier to debug. 

I'm not sure if you know how to use Visual Studio or not, so I don't give further instructions than that. 

Also, if you don't know how to debug it yourself, you could break into the debugger when it hangs, and copy all call stacks and paste them here.

**Comment by fredizzimo** [comment]
A log file was provided in:
* #2462 

> TRACE [neovide::renderer::vsync::vsync_macos] Window moved to a new screen, try to re-create the display link.
> TRACE [neovide::renderer::vsync::vsync_macos] Succeeded to create display link.
> TRACE [neovide::renderer::vsync::vsync_macos] Display link started.

So, it seems related to our display link vsync support.  Even if the log says that the window has been moved to another screen, that's not necessarily the case, it could also be a false alarm, and the internal state got messed up.

The whole renderer and vsync is being re-worked here by @crupest:
* https://github.com/neovide/neovide/pull/2461

So, the issue might already be solved there, and if not, it probably will, when the vsync is further improved.

**Comment by fredizzimo** [comment]
@ngseba, let's continue here

It looks like the communication with Neovim dies. 

This is the last indication of any communication happening
> TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <BS>

Can you test with the latest git version of Neovide ? There's a potential fix in nvim-rs https://github.com/KillTheMule/nvim-rs/pull/48, https://github.com/neovide/neovide/pull/2336

There was also a couple of problems in Neovim, that are fixed in Neovim nightly, so you could also check with that.

**Comment by ngseba** [comment]
So I built the release version of neovide from the latest main. As of the last commit, it is still reproducible. 

However, going back to [v0.11.2...v0.12.0](https://github.com/neovide/neovide/compare/0.11.2...0.12.0) where the issue started to occur. I found the problematic commit, it seems to be [this one](https://github.com/neovide/neovide/commit/b496ab23f4f5a20b494a1bd055eafe796324fd1d).

I couldn't reproduce on the [previous one at all](https://github.com/neovide/neovide/commit/2a1074b3610c07b637e6bce8afb48fccf0767e7b).

**Comment by fredizzimo** [comment]
In that case, there are two possible fixes, both requires Neovim nightly.

The first one is this:
* https://github.com/neovim/neovim/pull/27348

The second one is this Neovide PR with a very recent nightly build
* https://github.com/neovide/neovide/pull/2455

**Comment by ngseba** [comment]
You're right! I'm unsure which of those PR's got it working, but for me it does not reproduce. I checked it again on the latest neovide main branch, and on the latest version 0.12.2. It works well on both with neovim nightly.

**Comment by pidgeon777** [comment]
> In that case, there are two possible fixes, both requires Neovim nightly.
> 
> The first one is this:
> 
> * [fix: crashes with large msgpack messages neovim/neovim#27348](https://github.com/neovim/neovim/pull/27348)
> 
> The second one is this Neovide PR with a very recent nightly build
> 
> * [Handle new viewport margins event #2455](https://github.com/neovide/neovide/pull/2455)

I tried the Windows build here:

https://github.com/neovide/neovide/actions/runs/8527064563#artifacts

and Neovide on Windows 11 crash at startup:

**neovide_backtraces.log**:

```log
2024-04-04 06:29:25 - Neovide panicked with the message 'Failed to create Direct3D debug controller: ()'. (File: src\renderer\d3d.rs; Line: 161, Column: 10)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart
```

**Comment by fredizzimo** [comment]
@pidgeon777, I'm not sure why it's failing, it should direct3d itself should only enable those when debugging.

But if you can build from source, you could try deleting these lines:
https://github.com/neovide/neovide/blob/bcd913496924c0cfd5a99216dfb2abef2d25dcc3/src/renderer/d3d.rs#L158-L166

**Comment by pidgeon777** [comment]
Unfortunately, I can't build from sources, but version `0.12.2` works fine (except for the random freezes).

**Comment by pidgeon777** [comment]
> > In that case, there are two possible fixes, both requires Neovim nightly.
> > The first one is this:
> > 
> > * [fix: crashes with large msgpack messages neovim/neovim#27348](https://github.com/neovim/neovim/pull/27348)
> > 
> > The second one is this Neovide PR with a very recent nightly build
> > 
> > * [Handle new viewport margins event #2455](https://github.com/neovide/neovide/pull/2455)
> 
> I tried the Windows build here:
> 
> https://github.com/neovide/neovide/actions/runs/8527064563#artifacts
> 
> and Neovide on Windows 11 crash at startup:
> 
> **neovide_backtraces.log**:
> 
> ```
> 2024-04-04 06:29:25 - Neovide panicked with the message 'Failed to create Direct3D debug controller: ()'. (File: src\renderer\d3d.rs; Line: 161, Column: 10)
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: BaseThreadInitThunk
>   14: RtlUserThreadStart
> ```

If I understood correctly @fredizzimo, the fix you proposed above won't solve this startup crash?

**Comment by fredizzimo** [comment]
Yes, the random freeze. The startup crash can probably be fixed by deleting the lines I pasted above or using Neovide 12.2 instead of the git build.

**Comment by pidgeon777** [comment]
> Yes, the random freeze. The startup crash can probably be fixed by deleting the lines I pasted above or using Neovide 12.2 instead of the git build.

I posted an update here:

https://github.com/neovide/neovide/issues/2517

**Comment by axelhj** [comment]
This issue was definitely neovim, not neovide for me. Turning off treesitter indent, textobjects and a Comment.nvim integration seems to have resolved it for me without updating the build.

**Comment by pidgeon777** [comment]
Could it be that the latest Neovim and Neovide binary combination (built from source) doesn't cause the random freezes when using `--no-multigrid`, but does when that command option is removed? Because that seems to be what is happening on my Windows 11 Pro setup.

**Comment by fredizzimo** [comment]
The issue should be fixed in the latest nightly build of Neovim, the 0.9.5 version does not include my fix that I linked earlier:
* https://github.com/neovim/neovim/pull/27348

But there was also another regression after that, which caused similar symptoms:
* https://github.com/neovim/neovim/issues/27859

That one should be fixed, but unfortunately the reports both here and there are inconclusive. So, it would be important that we get a new Neovide log file if that still happens and can report so to the Neovim team, as the 0.10 release is quickly approaching for them. The log file will most likely contain enough information for me to determine if it's the same cause or not. Even better of course if someone that can reproduce it is able to debug the Neovim side of it, and report exactly what's wrong.

The debug controller thing is a separate bug, and can be fixed by commenting the lines as explained in this message, but I think that has changed slightly now since the code was refactored:
* https://github.com/neovide/neovide/issues/2384#issuecomment-2036377263. I have not made those changes myself, since I haven't been working on other stuff on Linux, so I haven't been on Windows to test the fixes.

**Comment by fredizzimo** [comment]
Can you all test with the latest Neovim nightly build from today? There's another potential fix here
* https://github.com/neovim/neovim/pull/28717

**Comment by pidgeon777** [comment]
@fredizzimo I tried the artifactories from here:

https://github.com/neovide/neovide/actions/runs/9047366796#artifacts

and now Neovide seems to hang a little bit before closing. Sometimes this even appears after quit:

![image](https://github.com/neovide/neovide/assets/13739892/6edf308c-6a88-4a95-9d07-9f3fa34dfab2)

Also, neovide.exe is not reported as running in Windows Task Manager, but some zombie process still exist, blocking the original .exe:

![image](https://github.com/neovide/neovide/assets/13739892/93e847da-f482-4c66-a070-c871a895050a)

**Comment by fredizzimo** [comment]
The fix is most likely fixed in Neovim 0.10.0 and since our new 0.13.0 release requires that, I'm closing this issue.

**Comment by snoblenet** [comment]
I can consistently reproduce the freezing behaviour with these steps:
- require("telescope.builtin").diagnostics()
- select an error to go do it
- dd to delete the line containing the error
- not necessary saving the buffer after this change
- require("telescope.builtin").diagnostics()

Using the latest:
- neovim
- neovide
- Mac OS X
- plugins, such as Telescope
