### ISSUE TITLE
Cannot launch neovide from MacOS Dock with `fish` set as system shell

### ISSUE THREAD

**Issue by Robert-Muil** [neovide/neovide#2840]
**Describe the bug**
Launching neovide from MacOS Dock with `fish` as system shell crashes with this error:
```
Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

ERROR: Unexpected output from neovim binary:
	 -v
stdout: 
stderr: fish: Unknown command: -v
fish: 
 -v
 ^^
	

Please check your shell configuration.
$SHELL -lc '{bin} -v'
```

**To Reproduce**
1. install neovide from brew
2. launch from cli (`$ neovide`)
3. click 'keep in dock' in dock
4. close neovide
5. click dock icon

**Expected behavior**
Expect neovide to launch as from CLI

**Screenshots**
entire error pasted above, nothing else to see

**Desktop (please complete the following information):**
 - OS: macOS 14.7 (Sonoma)
 - Neovide Version: 0.13.3
 - Neovim Version: 0.10.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I can't, github tells me the body is too long, body is too long. I've snipped the middle out:
```
TRACE [neovide] Neovide version: 0.13.3
DEBUG [neovide::settings::window_size] Loaded window settings: Windowed { position: PhysicalPosition { x: 5176, y: -592 }, pixel_size: Some(PhysicalSize { width: 2120, height: 2054 }), grid_size: Some(123x58) }
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/opt/homebrew/bin/nvim" "--embed" "-p", kill_on_drop: false }
INFO [neovide::bridge] Neovide registered to nvim with channel id 1
TRACE [neovide::settings] Initial value load failed for floating_blur: Error processing request: 1 - 'Key not found: neovide_floating_blur')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for theme: Error processing request: 1 - 'Key not found: neovide_theme')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for padding_top: Error processing request: 1 - 'Key not found: neovide_padding_top')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for text_contrast: Error processing request: 1 - 'Key not found: neovide_text_contrast')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for input_macos_alt_is_meta: Error processing request: 1 - 'Key not found: neovide_input_macos_alt_is_meta')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for touch_deadzone: Error processing request: 1 - 'Key not found: neovide_touch_deadzone')
TRACE [neovide::bridge::handler] Neovim notification: "setting_changed"
TRACE [neovide::settings] Initial value load failed for light_angle_degrees: Error processing request: 1 - 'Key not found: neovide_light_angle_degrees')

...

TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        KeyQ,
    ),
    logical_key: Character(
        "q",
    ),
    text: None,
    location: Standard,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "q",
        ),
        key_without_modifiers: Character(
            "q",
        ),
    },
}
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        ShiftRight,
    ),
    logical_key: Named(
        Shift,
    ),
    text: None,
    location: Right,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: None,
        key_without_modifiers: Named(
            Shift,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(SHIFT), pressed_mods: ModifiersKeys(RSHIFT) }
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 4 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        Digit1,
    ),
    logical_key: Character(
        "!",
    ),
    text: Some(
        "!",
    ),
    location: Standard,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "!",
        ),
        key_without_modifiers: Character(
            "1",
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Key pressed ! ModifiersState(SHIFT)
TRACE [neovide::channel_utils] UIComand Serial(Keyboard("!"))
TRACE [neovide::bridge::ui_commands] In Serial Command
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: !
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 3, row: 0, column_start: 2, cells: [GridLineCell { text: "!", highlight_id: Some(1), repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler CursorGoto { grid: 3, row: 0, column: 3 }
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text: ":q!"
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        ShiftRight,
    ),
    logical_key: Named(
        Shift,
    ),
    text: None,
    location: Right,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: None,
        key_without_modifiers: Named(
            Shift,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        Digit1,
    ),
    logical_key: Character(
        "1",
    ),
    text: None,
    location: Standard,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "1",
        ),
        key_without_modifiers: Character(
            "1",
        ),
    },
}
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        Enter,
    ),
    logical_key: Named(
        Enter,
    ),
    text: Some(
        "\r",
    ),
    location: Standard,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "\r",
        ),
        key_without_modifiers: Named(
            Enter,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Key pressed <Enter> ModifiersState(0x0)
TRACE [neovide::channel_utils] UIComand Serial(Keyboard("<Enter>"))
TRACE [neovide::bridge::ui_commands] In Serial Command
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <Enter>
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler CursorGoto { grid: 3, row: 0, column: 0 }
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::bridge::handler] Neovim request: "neovide.quit"
INFO [neovide::running_tracker] Quit with code 0: Quit from neovim
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler ModeChange { mode: Normal, mode_index: 0 }
TRACE [neovide::channel_utils] neovim_handler MouseOn
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
DEBUG [neovide::renderer] zindex: 250, base: 0
DEBUG [neovide::renderer] layer: [(3, SortOrder { z_index: 250, composition_order: 5 })]
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 2030.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 2030.0 }, pics: 1
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 0.0), (2119.3845, 1960.0)), inner: Rect { left: 0.0, top: 0.0, right: 2119.3845, bottom: 1960.0 }, pics: 55
TRACE [neovide::renderer::rendered_window] region: Box2D((0.0, 1995.0), (2119.3845, 4025.0)), inner: Rect { left: 0.0, top: 1995.0, right: 2119.3845, bottom: 4025.0 }, pics: 1
INFO [neovide::bridge] Neovim has quit
DEBUG [neovide::settings::window_size] Saved Window Settings: {"window":{"Windowed":{"position":{"x":5176,"y":-592},"pixel_size":{"width":2120,"height":2054},"grid_size":[123,58]}}}
```

**Additional context**
I have `/opt/homebrew/bin/fish` set as my default login shell.

**Comment by Robert-Muil** [comment]
Confirmed that resetting my shell to zsh (reboot required, oddly) caused this to disappear.

**Comment by NGPONG** [comment]
same

**Comment by r-darwish** [comment]
Same problem in nushell:

```
Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

ERROR: Unexpected output from neovim binary:
	/opt/homebrew/bin/nvim -v
stdout: 
stderr: Error: [31mnu::parser::missing_flag_param[0m

  [31m×[0m Missing flag argument.
   ╭─[[36;1;4msource[0m:1:4]
 [2m1[0m │ nu -lc
   · [35;1m   ─┬─[0m
   ·     [35;1m╰── [35;1mflag missing string argument[0m[0m
   ╰────

	

Please check your shell configuration.
$SHELL -lc '{bin} -v'
```

I don't know about fish but nushell doesn't support `-lc` (arguments have to be specified individually `-l -c`)

**Comment by eikopf** [comment]
just throwing out there that i ran into the same issue with both `fish` *and* `zsh`, but Neovide started properly with `fish` as the login shell after a restart. Seems like the issue might be with how Neovide finds the login shell?

**Comment by ngpong** [comment]
Hey guys, is there any workaround for this?

**Comment by fredizzimo** [comment]
@falcucci, I really belive we have to use zsh for the login command, just like Alacritty for example, and that I suggested here https://github.com/neovide/neovide/pull/2405#discussion_r1518355410

**Comment by fredizzimo** [comment]
Here's the alacritty code
```rs
    // On macOS, use the `login` command so the shell will appear as a tty session.
    let mut login_command = Command::new("/usr/bin/login");

    // Exec the shell with argv[0] prepended by '-' so it becomes a login shell.
    // `login` normally does this itself, but `-l` disables this.
    let exec = format!("exec -a -{} {}", shell_name, shell);

    // -f: Bypasses authentication for the already-logged-in user.
    // -l: Skips changing directory to $HOME and prepending '-' to argv[0].
    // -p: Preserves the environment.
    //
    // XXX: we use zsh here over sh due to `exec -a`.
    login_command.args(["-flp", user, "/bin/zsh", "-fc", &exec]);
    login_command
```

And our https://github.com/neovide/neovide/blob/458af94b59acb50df6257b8bdb4ae05bb11c7e25/src/bridge/command.rs#L47-L90

**Comment by falcucci** [comment]
Sure @fredizzimo 

The actual problem here is bringing the correct flags for every specific shell which is not clever from our perspective, but just executing the login using zsh will force the chosen user shell to be loaded correctly. (tested from my bash shell rn)

**Comment by falcucci** [comment]
I'll update it and ask someone here using fish shell to test the artifact.

**Comment by fredizzimo** [comment]
> The actual problem here is bringing the correct flags for every specific shell which is not clever from our perspective, but just executing the login using zsh will force the chosen user shell to be loaded correctly. (tested from my bash shell rn)

Yes, bot that and the lack of exec are problems, and the Alacritty code solves both by not needing to pass any flags to the user shell.

**Comment by falcucci** [comment]
can someone using `fish` install [this](https://github.com/neovide/neovide/actions/runs/12610456067?pr=2928) artifact and try to launch again? maybe @ngpong

**Comment by fredizzimo** [comment]
The latest executables can be found at the bottom of this page 
https://github.com/neovide/neovide/actions/runs/12611813099

**Comment by ngpong** [comment]
Wow, thanks to the community for picking up on this already @fredizzimo @falcucci . I tried the latest ci package and unfortunately the error remains! 

Here's my error log, although it looks the same as before, not quite sure if that helps; my environment is win11 WSL2 Ubuntu24.04, Please feel free to let me know if I'm missing anything.

```
TRACE [neovide] Neovide version: 0.14.0
DEBUG [neovide::settings::window_size] Loaded window settings: Maximized { grid_size: Some(Size2 { width: 156, height: 41 }) }
DEBUG [neovide::bridge::command] Running which command: "wsl" "$SHELL" "-lc" "which nvim"
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

ERROR: Unexpected output from neovim binary:
        /usr/bin/nvim -v
stdout:
stderr: fish: Unexpected end of string, square brackets do not match
/usr/bin/nvim -v
     ^


Please check your WSL configuration.
wsl '$SHELL' -lc '{bin} -v'
```

Anyway, it's a start as far as best wishes go!

**Comment by fredizzimo** [comment]
Ah, that's one thing that I forgot to mention, I noticed that we have a similar bug on wsl as well, but only macOS is fixed here.

**Comment by ngpong** [comment]
my situation does deviate slightly from the topic issuse mentioned, and I apologize for not mentioning my circumstances at the beginning. 🙏🙏

**Comment by falcucci** [comment]
@ngpong thank you, I guess by now we need @Robert-Muil itself to test this?

**Comment by diocletiann** [comment]
I'm not able to replicate this. Steps taken:

-Installed brew case (which pulls in neovim...)
-Launched from fish (Ghostty terminal)
-set "Keep in Dock"
-Click icon

Neovide opens as intended

**Comment by ngpong** [comment]
I tried the latest commit https://github.com/neovide/neovide/pull/2928 unfortunately it still doesn't work in a wsl environment. However it was able to get to work as expected by changing `config.fish` to the follow. hope this helps anyone who needs it !

```fish
if status is-interactive
  # {{ All my old `config.fish` contents }}
end
```

Anyway, thanks for all your great work @falcucci @fredizzimo 

Best wishes !

**Comment by ngpong** [comment]
Hey @sss, thanks for your reply! Sorry for the late response due to the time difference.

> did you get the same message as the OP? I think that you should have received something like ERROR: Unexpected output from neovim binary

Yes, as shown in this comment https://github.com/neovide/neovide/issues/2840#issuecomment-2571398040, I received the same error output as the OP. The only difference is that I’m using a WSL environment, unlike the OP. I apologize if this caused any confusion in our discussion!

> And yes for fish, that's the correct way to exclude things.

So, can I understand that the correct solution to the problem is to specify the configuration file for use only in interactive mode?

**Comment by fredizzimo** [comment]
Hm, that still looks strange, and it looks like we have some problems with the error reporting, but I'm unable to investigate myself for some time, I'm on vaccation and don't have a development computer available.

When running wsl or on macOS, Neovide has to launch a login shell before launching Neovide, otherwise environment variables like the path won't be set. And since the communication happens through stdout, then we have to ensure that no additional output is shown, like output from `neofetch` and similar. Therefore, we launch a non-interactive login shell, assuming that the user has configured that correctly to not output anything.

So, you can still run most of your normal fish configuration, you just have to disable the parts that outputs stuff. And that's what the error message is supposed to show, but in your case it looks more like a syntax error launching the actual command, than output from the shell startup.

**Comment by ngpong** [comment]
> And since the communication happens through stdout, then we have to ensure that no additional output is shown, like output from neofetch and similar.

Thank you @fredizzimo for taking the time to follow up on this issue. Based on the clue you provided, I found that simply commenting out the following few lines fixes the problem (without needing to wrap them in the status is-interactive scope). It seems that these two commands are interfering with the stdout output.

```fish
# printf "\e[?12l"

# # brew
# if not test -d "/home/linuxbrew/.linuxbrew" && not test -d "$HOME/.linuxbrew"
#   /bin/bash -c "(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# end
# /home/linuxbrew/.linuxbrew/bin/brew shellenv | source
```

> it looks like we have some problems with the error reporting

Once again, I apologize for not following proper error reporting guidelines.

> I'm on vaccation and don't have a development computer available.

I feel like I’m one step closer to the truth, and I will continue investigating (it would be great if you could offer some help!). I hope you have a wonderful vaccation, and there’s no rush on this from my side.

**Comment by fredizzimo** [comment]
For the homebrew/linuxbrew issue, see this https://github.com/neovide/neovide/issues/2741
