### ISSUE TITLE
Segfaults at exit on Wayland due to clipboard deletion

### ISSUE THREAD

**Issue by fredizzimo** [neovide/neovide#3318]
The current Neovide master crashes 100% of the time on exit due to the clipboard being deleted *after* the Winit event loop. That's not allowed since the clipboard internally uses the wayland connection, which is managed by the Winit event loop.

Reverting to 11aeb0f877139aa1301a0cd5dc8b2aadda6c5224 fixes the issue, but it's still broken and sproadically crashes with `--version` or `--help`.

The callstack is the following:
```
___lldb_unnamed_symbol165 (@___lldb_unnamed_symbol165:23)
___lldb_unnamed_symbol166 (@___lldb_unnamed_symbol166:79)
wl_proxy_destroy (@wl_proxy_destroy:17)
wayland_backend::sys::client_impl::InnerBackend::send_request (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wayland-backend-0.3.11/src/sys/client_impl/mod.rs:719)
wayland_backend::sys::client::Backend::send_request (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wayland-backend-0.3.11/src/client_api.rs:239)
wayland_client::conn::Connection::send_request (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wayland-client-0.31.11/src/conn.rs:201)
wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wayland-protocols-0.32.9/src/protocol_macro.rs:28)
<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smithay-client-toolkit-0.20.0/src/primary_selection/mod.rs:80)
core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:804)
core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:804)
core::ptr::drop_in_place<smithay_clipboard::state::State> (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:804)
smithay_clipboard::worker::worker_impl (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smithay-clipboard-0.7.3/src/worker.rs:101)
smithay_clipboard::worker::spawn::{{closure}} (/home/fredizzimo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smithay-clipboard-0.7.3/src/worker.rs:23)
std::sys::backtrace::__rust_begin_short_backtrace (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:158)
std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}} (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559)
<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274)
std::panicking::catch_unwind::do_call (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:590)
__rust_try (@__rust_try:10)
std::panicking::catch_unwind (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:553)
std::panic::catch_unwind (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359)
std::thread::Builder::spawn_unchecked_::{{closure}} (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557)
core::ops::function::FnOnce::call_once{{vtable.shim}} (/home/fredizzimo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250)
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once (@std::sys::thread::unix::Thread::new::thread_start:19)
std::sys::thread::unix::Thread::new::thread_start (@std::sys::thread::unix::Thread::new::thread_start:17)
___lldb_unnamed_symbol3734 (@___lldb_unnamed_symbol3734:156)
___lldb_unnamed_symbol4176 (@___lldb_unnamed_symbol4176:6)
```

Note that `event_loop.run_app` take ownership of `self`, so the event loop is already destroyed when the function returns. This esentially means that the cleanup has to be performed in `ApplicationHandler::exiting`.

That's the primary reason why I made https://github.com/neovide/neovide/pull/3252, so that the lifetimes of the systems can be better controlled, even when there's eventually multiple runtimes and renders due to multigrid support. I strongly suggest that you revert the two clipboard lifetime changes you made and take a second look at the PR in question, since it cleans up a lot of other things as well. Note that it looks bigger than it is due to mostly naming changes.  

If it's merged, it will also greatly reduce the size of the multi-window PR, since it eliminates all that focused`route clutter, the events would simply be directly sent to the correct update loop. There's also no need for globals like `HANDLER_REGISTRY`, when the `NeovimWindow` simply owns its own handler.

**Comment by falcucci** [comment]
thanks for the report,

I have looked already your pull request multiple times and honestly is much more than a fix and have some similarities with the multi-window refactor approach that i'll avoid to merge as it is, baby steps will be applied.

me and @ewhac have [tested](https://github.com/neovide/neovide/issues/3311#issuecomment-3597758854) this on Wayland and we didnt have had even a hiccup there after the fix for --version and --help so I'll mark this as duplicated, but let's interact in a already known issue and if it's the case i'll reopen it.


I'll also try to reproduce your case soon when I have some time and when I have access to Wayland again.

**Comment by fredizzimo** [comment]
I don't see any tests where you ran without `--version` or `--help`.  They seem to work now, since that only relies on the drop order of the function arguments. But running neovide normally, for example `neovide -- --clean`  crashes. Does that really work for you  @ewhac?

Adding drop to the update loop does nothing to fix the issue, it's called here

https://github.com/neovide/neovide/blob/d090aa45d5a331b1141868554ef7011ae7dde0e4/src/main.rs#L140

And, the event loop is destroyed here
https://github.com/neovide/neovide/blob/d090aa45d5a331b1141868554ef7011ae7dde0e4/src/main.rs#L134

NOTE: The situation is different in winit 0.31 https://github.com/rust-windowing/winit/pull/3721, but Neovide still use Winit 0.30, which takes the app by reference.

**Comment by fredizzimo** [comment]
The error window also crashes with for example `neovide --fork --neovim-bin nonexisting_nvim`

**Comment by Kethku** [comment]
Reopening this instead of carrying forward on the other issue. I think theres context here thats still worth tracking

**Comment by falcucci** [comment]
@paulobressan do you mind sending your feedback on this issue here as well?

**Comment by paulobressan** [comment]
Sorry for the delay to check this out! I have tried to reproduce everything using Wayland on two computers, one using the Mesa driver and another one using Nvidia driver.
> Reverting to 11aeb0f fixes the issue, but it's still broken and sporadically crashes with --version or --help.

At my tests, since the fix that @falcucci has done at https://github.com/neovide/neovide/pull/3313 this doesn't happen anymore on Wayland and reverting it was not needed for me, and the following commands worked perfectly.

```
for i in {1..1000}; do ./target/release/neovide --version; done
```

```
for i in {1..1000}; do ./target/release/neovide --help; done
```

> The current Neovide master crashes 100% of the time on exit due to the clipboard being deleted after the Winit event loop.

I have fixed this issue https://github.com/neovide/neovide/pull/3319 and is already merged in the main branch.

And now I propose this change https://github.com/neovide/neovide/pull/3321 to improve how the error window handles the clipboard.

```
./target/release/neovide --fork --neovim-bin nonexisting_nvim
```

Finally, all commands work for me.

```
./target/release/neovide -- --clean
./target/release/neovide --version
./target/release/neovide --help
./target/release/neovide --fork --neovim-bin non/existing/neovim/path
```

**Comment by fredizzimo** [comment]
Thank you @paulobressan. I can confirm that https://github.com/neovide/neovide/pull/3321 now fixes the error window exit as well. I also checked the commit prior to confirm that I was not seeing ghosts, and yes that still crashes for me. Note that you need to check with a debugger or journalctl, since the process is forked, the shell does not report the crash.
